[package]
name = "sparser"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter="0.20.4"
rand="0.8"
regex="1"
clap={version="3.1", features=["derive"]}
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
walkdir = "2"


[build-dependencies]
cc="*"
